//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace XpoTools.master
{

    public partial class IPLI_EXM_ATT_FILE : XPBaseObject
    {
        string fCASE_SEQ_NO;
        [Key]
        [Size(50)]
        public string CASE_SEQ_NO
        {
            get { return fCASE_SEQ_NO; }
            set { SetPropertyValue<string>("CASE_SEQ_NO", ref fCASE_SEQ_NO, value); }
        }
        int fITEM_NO;
        public int ITEM_NO
        {
            get { return fITEM_NO; }
            set { SetPropertyValue<int>("ITEM_NO", ref fITEM_NO, value); }
        }
        string fFILE_NAME;
        [Size(50)]
        public string FILE_NAME
        {
            get { return fFILE_NAME; }
            set { SetPropertyValue<string>("FILE_NAME", ref fFILE_NAME, value); }
        }
        string fFILE_TYPE;
        [Size(50)]
        public string FILE_TYPE
        {
            get { return fFILE_TYPE; }
            set { SetPropertyValue<string>("FILE_TYPE", ref fFILE_TYPE, value); }
        }
        string fFILE_PATH;
        [Size(50)]
        public string FILE_PATH
        {
            get { return fFILE_PATH; }
            set { SetPropertyValue<string>("FILE_PATH", ref fFILE_PATH, value); }
        }
        string fFILE_MEMO;
        [Size(50)]
        public string FILE_MEMO
        {
            get { return fFILE_MEMO; }
            set { SetPropertyValue<string>("FILE_MEMO", ref fFILE_MEMO, value); }
        }
        string fHL7;
        [Size(50)]
        public string HL7
        {
            get { return fHL7; }
            set { SetPropertyValue<string>("HL7", ref fHL7, value); }
        }
        string fSHORT_CUT_STATUS;
        [Size(50)]
        public string SHORT_CUT_STATUS
        {
            get { return fSHORT_CUT_STATUS; }
            set { SetPropertyValue<string>("SHORT_CUT_STATUS", ref fSHORT_CUT_STATUS, value); }
        }
        string fFILE_PATH_REF;
        [Size(50)]
        public string FILE_PATH_REF
        {
            get { return fFILE_PATH_REF; }
            set { SetPropertyValue<string>("FILE_PATH_REF", ref fFILE_PATH_REF, value); }
        }
        int fFILE_OPEN_APP;
        public int FILE_OPEN_APP
        {
            get { return fFILE_OPEN_APP; }
            set { SetPropertyValue<int>("FILE_OPEN_APP", ref fFILE_OPEN_APP, value); }
        }
        string fORIG_FILE_NAME;
        [Size(50)]
        public string ORIG_FILE_NAME
        {
            get { return fORIG_FILE_NAME; }
            set { SetPropertyValue<string>("ORIG_FILE_NAME", ref fORIG_FILE_NAME, value); }
        }
        string fFILE_ATTACH;
        [Size(50)]
        public string FILE_ATTACH
        {
            get { return fFILE_ATTACH; }
            set { SetPropertyValue<string>("FILE_ATTACH", ref fFILE_ATTACH, value); }
        }
        string fDOCUMENT_TYPE;
        [Size(50)]
        public string DOCUMENT_TYPE
        {
            get { return fDOCUMENT_TYPE; }
            set { SetPropertyValue<string>("DOCUMENT_TYPE", ref fDOCUMENT_TYPE, value); }
        }
        string fERR_CODE;
        [Size(50)]
        public string ERR_CODE
        {
            get { return fERR_CODE; }
            set { SetPropertyValue<string>("ERR_CODE", ref fERR_CODE, value); }
        }
        string fFILE_PATH_TC;
        [Size(50)]
        public string FILE_PATH_TC
        {
            get { return fFILE_PATH_TC; }
            set { SetPropertyValue<string>("FILE_PATH_TC", ref fFILE_PATH_TC, value); }
        }
        string fFILE_PATH_REF_TC;
        [Size(50)]
        public string FILE_PATH_REF_TC
        {
            get { return fFILE_PATH_REF_TC; }
            set { SetPropertyValue<string>("FILE_PATH_REF_TC", ref fFILE_PATH_REF_TC, value); }
        }
        string fORIG_FILE_MD5;
        [Size(50)]
        public string ORIG_FILE_MD5
        {
            get { return fORIG_FILE_MD5; }
            set { SetPropertyValue<string>("ORIG_FILE_MD5", ref fORIG_FILE_MD5, value); }
        }
        string fORIG_FILE_MD5_CHECK_FLAG;
        [Size(50)]
        public string ORIG_FILE_MD5_CHECK_FLAG
        {
            get { return fORIG_FILE_MD5_CHECK_FLAG; }
            set { SetPropertyValue<string>("ORIG_FILE_MD5_CHECK_FLAG", ref fORIG_FILE_MD5_CHECK_FLAG, value); }
        }
        DateTime fORIG_FILE_MD5_CHECK_TIME;
        public DateTime ORIG_FILE_MD5_CHECK_TIME
        {
            get { return fORIG_FILE_MD5_CHECK_TIME; }
            set { SetPropertyValue<DateTime>("ORIG_FILE_MD5_CHECK_TIME", ref fORIG_FILE_MD5_CHECK_TIME, value); }
        }
        string fCONVERT_FILE_MD5;
        [Size(50)]
        public string CONVERT_FILE_MD5
        {
            get { return fCONVERT_FILE_MD5; }
            set { SetPropertyValue<string>("CONVERT_FILE_MD5", ref fCONVERT_FILE_MD5, value); }
        }
        string fCONVERT_FILE_TP_STATUS;
        [Size(50)]
        public string CONVERT_FILE_TP_STATUS
        {
            get { return fCONVERT_FILE_TP_STATUS; }
            set { SetPropertyValue<string>("CONVERT_FILE_TP_STATUS", ref fCONVERT_FILE_TP_STATUS, value); }
        }
        string fCONVERT_FILE_TP_PATH;
        [Size(50)]
        public string CONVERT_FILE_TP_PATH
        {
            get { return fCONVERT_FILE_TP_PATH; }
            set { SetPropertyValue<string>("CONVERT_FILE_TP_PATH", ref fCONVERT_FILE_TP_PATH, value); }
        }
        string fCONVERT_FILE_MD5_TP_CHECK_FLAG;
        [Size(50)]
        public string CONVERT_FILE_MD5_TP_CHECK_FLAG
        {
            get { return fCONVERT_FILE_MD5_TP_CHECK_FLAG; }
            set { SetPropertyValue<string>("CONVERT_FILE_MD5_TP_CHECK_FLAG", ref fCONVERT_FILE_MD5_TP_CHECK_FLAG, value); }
        }
        DateTime fCONVERT_FILE_MD5_TP_CHECK_TIME;
        public DateTime CONVERT_FILE_MD5_TP_CHECK_TIME
        {
            get { return fCONVERT_FILE_MD5_TP_CHECK_TIME; }
            set { SetPropertyValue<DateTime>("CONVERT_FILE_MD5_TP_CHECK_TIME", ref fCONVERT_FILE_MD5_TP_CHECK_TIME, value); }
        }
        string fCONVERT_FILE_TC_STATUS;
        [Size(50)]
        public string CONVERT_FILE_TC_STATUS
        {
            get { return fCONVERT_FILE_TC_STATUS; }
            set { SetPropertyValue<string>("CONVERT_FILE_TC_STATUS", ref fCONVERT_FILE_TC_STATUS, value); }
        }
        string fCONVERT_FILE_TC_PATH;
        [Size(50)]
        public string CONVERT_FILE_TC_PATH
        {
            get { return fCONVERT_FILE_TC_PATH; }
            set { SetPropertyValue<string>("CONVERT_FILE_TC_PATH", ref fCONVERT_FILE_TC_PATH, value); }
        }
        string fCONVERT_FILE_MD5_TC_CHECK_FLAG;
        [Size(50)]
        public string CONVERT_FILE_MD5_TC_CHECK_FLAG
        {
            get { return fCONVERT_FILE_MD5_TC_CHECK_FLAG; }
            set { SetPropertyValue<string>("CONVERT_FILE_MD5_TC_CHECK_FLAG", ref fCONVERT_FILE_MD5_TC_CHECK_FLAG, value); }
        }
        DateTime fCONVERT_FILE_MD5_TC_CHECK_TIME;
        public DateTime CONVERT_FILE_MD5_TC_CHECK_TIME
        {
            get { return fCONVERT_FILE_MD5_TC_CHECK_TIME; }
            set { SetPropertyValue<DateTime>("CONVERT_FILE_MD5_TC_CHECK_TIME", ref fCONVERT_FILE_MD5_TC_CHECK_TIME, value); }
        }
    }

}
