//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace XpoTools.master
{

    public partial class PXXT_CODE : XPBaseObject
    {
        string fSUB_SYS;
        [Key]
        [Size(50)]
        public string SUB_SYS
        {
            get { return fSUB_SYS; }
            set { SetPropertyValue<string>("SUB_SYS", ref fSUB_SYS, value); }
        }
        string fDATA_TYPE;
        [Size(50)]
        public string DATA_TYPE
        {
            get { return fDATA_TYPE; }
            set { SetPropertyValue<string>("DATA_TYPE", ref fDATA_TYPE, value); }
        }
        string fCODE;
        [Size(50)]
        public string CODE
        {
            get { return fCODE; }
            set { SetPropertyValue<string>("CODE", ref fCODE, value); }
        }
        string fCODE_CNAME;
        [Size(50)]
        public string CODE_CNAME
        {
            get { return fCODE_CNAME; }
            set { SetPropertyValue<string>("CODE_CNAME", ref fCODE_CNAME, value); }
        }
        string fCODE_ENAME;
        [Size(50)]
        public string CODE_ENAME
        {
            get { return fCODE_ENAME; }
            set { SetPropertyValue<string>("CODE_ENAME", ref fCODE_ENAME, value); }
        }
        DateTime fVALID_S_DATE;
        public DateTime VALID_S_DATE
        {
            get { return fVALID_S_DATE; }
            set { SetPropertyValue<DateTime>("VALID_S_DATE", ref fVALID_S_DATE, value); }
        }
        DateTime fVALID_E_DATE;
        public DateTime VALID_E_DATE
        {
            get { return fVALID_E_DATE; }
            set { SetPropertyValue<DateTime>("VALID_E_DATE", ref fVALID_E_DATE, value); }
        }
        string fTXT_STATUS;
        [Size(50)]
        public string TXT_STATUS
        {
            get { return fTXT_STATUS; }
            set { SetPropertyValue<string>("TXT_STATUS", ref fTXT_STATUS, value); }
        }
        string fEXE_TIME;
        [Size(50)]
        public string EXE_TIME
        {
            get { return fEXE_TIME; }
            set { SetPropertyValue<string>("EXE_TIME", ref fEXE_TIME, value); }
        }
        string fTXT_USR_ID;
        [Size(50)]
        public string TXT_USR_ID
        {
            get { return fTXT_USR_ID; }
            set { SetPropertyValue<string>("TXT_USR_ID", ref fTXT_USR_ID, value); }
        }
        string fBRANCH_CODE;
        [Size(50)]
        public string BRANCH_CODE
        {
            get { return fBRANCH_CODE; }
            set { SetPropertyValue<string>("BRANCH_CODE", ref fBRANCH_CODE, value); }
        }
        string frowid;
        public string rowid
        {
            get { return frowid; }
            set { SetPropertyValue<string>("rowid", ref frowid, value); }
        }
    }

}
